export const Icons = {
  //   icon__0: { idx: 0, src: require("./src/images/userIcon-0.png") },
  icon__1: { idx: 1, src: require("./src/images/userIcon-1.png") },
  icon__2: { idx: 2, src: require("./src/images/userIcon-2.png") },
  icon__3: { idx: 3, src: require("./src/images/userIcon-3.png") },
  icon__4: { idx: 4, src: require("./src/images/userIcon-4.png") },
  icon__5: { idx: 5, src: require("./src/images/userIcon-5.png") },
  icon__6: { idx: 6, src: require("./src/images/userIcon-6.png") },
  icon__7: { idx: 7, src: require("./src/images/userIcon-7.png") },
  icon__8: { idx: 8, src: require("./src/images/userIcon-8.png") },
  icon__9: { idx: 9, src: require("./src/images/userIcon-9.png") },
  icon__10: { idx: 10, src: require("./src/images/userIcon-10.png") },
  icon__11: { idx: 11, src: require("./src/images/userIcon-11.png") },
  icon__12: { idx: 12, src: require("./src/images/userIcon-12.png") },
};
